[project]
name = "name4py"
version = "0.1.1"
description = "Generate names in every language."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gdown",
    "vortezwohl>=0.0.2",
]
